### ISSUE TITLE
Improve navigation around the hierarchy

### ISSUE THREAD

**Issue by vsaarinen** [lucified/minard-ui#196]
When moving into, out of, or across projects/branches, it is sometimes unclear to the user where they are located. Many of the views look very similar. This should be made much more clear.

There are at least three directions this could be tackled from:
1. How to navigate around the hierarchy.
2. How to visually indicate to users where they are.
3. How to use transitions to indicate where a user is navigating to.

**Comment by pekkapulli** [comment]
Aside from transitions, this is better now. I'll create a separate issue for transitions.
